ihmeuw-scicomp/jobmon

jobmon_distributor/src/jobmon/distributor/distributor_instance.py
jobmon_server/src/jobmon/server/web/routes/fsm/batch.py
jobmon_server/src/jobmon/server/web/routes/fsm/distributor_instance.py
tests/distributor/conftest.py
tests/distributor/test_synchronization.py

The distributor should not consider task instances belonging to inactive workflow runs for any monitoring or launching work. This PR adds an endpoint to return registered batches associated with inactive workflow runs, and purge the distributor's memory space.

Gbdsci 5052/expire inactive task instances

---

jobmon_gui/src/progress_bar.tsx

Change the pop up to say "No Limit" instead of 2147483647 for max concurrency limit. After vs before screen shots.

Change to no limit

---

jobmon_gui/src/task_details_page/task_instance_table.tsx
jobmon_server/src/jobmon/server/web/routes/cli/task.py

We  have error logs in two places task_instance_error_log.description and task_instance.stderr_log. We currently display both in the error logs pop up modal but only one in the TaskInstance table pop up modal. So added the second location there.

Add second error log

---

jobmon_gui/src/workflow_details_page/errors.tsx
jobmon_gui/src/workflow_overview_page/workflow_overview.tsx

Took awhile to figure out what the problem was for this one, but it ended up being an easy fix. 
Adam submitted this ticket: https://help.ihme.washington.edu/projects/SCICOMP/queues/custom/164/SCICOMP-811
TLDR: the pop up modal for error logs on the WorkflowDetails page were showing the wrong error message and task IDs
Fundamentally was a pagination problem. Previously, we sent row index to the modal so it would know what information to show. This would work if there was only page of pagination. The problem happened when there were multiple pages. The reason for this was the the table component would have the row index be for the specific page not the overall data for the table. e.g. would have and index of 8 instead of 18. So when it was queried it would always populate with error logs …

Fix bug in errors tab

---

.flake8
jobmon_server/src/jobmon/server/web/routes/cli/task.py
jobmon_server/src/jobmon/server/web/routes/cli/workflow.py

A while back Adam mentioned that there were a couple of thousand linting errors in Jobmon. I realized when I was working in onemod that Jobmon was probably missing it's .flake8 config (lost in the migration to GitHub).
I re-added the config file and then fixed the handful of legitimate linting errors. Jobmon linting is now passing.

Re-add .flake8 config file to Jobmon

---

jobmon_client/src/jobmon/client/cli.py
jobmon_client/src/jobmon/client/status_commands.py
jobmon_client/src/jobmon/client/workflow_run.py
jobmon_server/src/jobmon/server/web/models/workflow.py
jobmon_server/src/jobmon/server/web/models/workflow_run.py
jobmon_server/src/jobmon/server/web/routes/cli/workflow.py
tests/cli/test_cli_routes.py

Fixes a bug where workflow reset doesn't reset workflowrun statuses, meaning if the most recent workflowrun is in cold resume and the reaper is behind or inactive the user cannot set a resumable state on the workflow. 
As a small enhancement added a flag for users to indicate whether a full or partial reset should be performed, defaulting to full. A full reset sets "D" tasks to registering, whereas a partial reset does not. The former is desired if a user wants to use the same DAG to regenerate an existing results set, whereas the latter is for setting a workflow in a weird state into a resumable state.

Gbdsci 5360/reset wfr status

---

jobmon_gui/package-lock.json
jobmon_gui/src/task_details_page/task_instance_table.tsx
jobmon_gui/src/workflow_overview_page/wf_table.tsx

Old hoverzoom was cutting off half of the statuses, changed to modal to be a better user experience.
Upped default pagination number from 10 -> 50, per user request.

Change TI statuses from hover zoom to modal, up pagination to 50

---

CHANGELOG.md
jobmon_gui/CHANGELOG.md

Added changelogs for Jobmon and the Jobmon GUI. Populated with information pulled from HUB release notes. I need to re-start tagging the Jobmon GUI releases like I used to do in stash.

Add changelogs

---

jobmon_client/src/jobmon/client/cli.py
jobmon_client/src/jobmon/client/status_commands.py

For large pipeline resumes, we needed access to the resume timeout.
This PR exposes that to the CLI so we don't need to hack our install.

Adds timeout to resume CLI.

---

jobmon_server/src/jobmon/server/web/routes/fsm/workflow.py

~Still need to test - nox tests do not work for me anymore, I think the web service utilites were never updated with the configuration updates.~ 
Prequery the initial ID for performance reasons. The cli/test_status_commands::test-resume_workflow_from_cli and the swarm/test_build_swarm_from_workflow_id tests both pass.

Prequery for initial task id

---

jobmon_core/src/jobmon/core/defaults.yaml
jobmon_server/pyproject.toml

Adds a dependency on core[otlp] in the server and adds a required reaper: poll_interval_minutes key in the defaults file

add necessary reaper config key, specify otlp optional dependency

---

jobmon_core/pyproject.toml
jobmon_core/src/jobmon/core/otlp.py

"import loggin.config" seems to fix the "logging.config" not found issue.
Revert the openelementry install.

Otlp client

---

jobmon_core/pyproject.toml
jobmon_gui/README.md
noxfile.py

I'm working through the setup for the gui developer environment and running into bugs.  PRing fixes as I find them.
Two changes here:
- It seems some telemetry was added to jobmon core, but some of the telemetery dependencies were not put into the pyproject.toml for jobmon_core.  So this adds those in and then updates the noxfile to make sure the extra telemetry dependencies get installed in the development environment (otherwise the `functionaltest_server.py` fails on import errors).
- Update the readme to use the python created by nox to run the test server.

Add missing dependencies to gui test environment setup

---

jobmon_server/src/jobmon/server/web/routes/v2/cli/workflow.py

when an inner WHERE clause is not provided the current code is throwing this error:
(MySQLdb.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')\n                    GROUP BY\n                        workflow_id, queue_id\n   ' at line 32")

changes to workflow.py sql query pass all nox client tests

---

jobmon_core/src/jobmon/core/task_generator.py
noxfile.py
tests/worker_node/test_task_generator.py

This PR is trying to fix these three issues:
1. GBDSCI-6420 - No naming args support
There is no actual function change, and it seems the previous rounds had already include this with test case, but I modified the code slightly to match the latest version of FHS.
2. GBDSCI-6419 - add task template deferral
There is function change to move the task template creation to when the first task creation, and added a few test cases. 
3. GBDSCI-6421 - Modify get_tasks_with_node_args to support object input
There is actual code change for this one. I have no idea why I had the serializer removed from get_tasks_with_node_args in previous rounds, which doesn't make any sense. My best guess is I might remove it for debugging, but forgot to add it back, so added a few test cases for this one too.

Task Generator Round 3 Part 1

---

.github/workflows/python-publish.yml
jobmon_client/README.md
jobmon_client/pyproject.toml
jobmon_core/README.md
jobmon_core/pyproject.toml
jobmon_server/README.md
jobmon_server/pyproject.toml
noxfile.py

Modified the python-publish.yml workflow to use "trusted publisher" to publish to pypi.org.  Lots of configuration in pypi.org to support this. Also created a new environment in github actions: pypi-prod.

Upload to pypi

---

jobmon_server/src/jobmon/server/web/routes/v2/cli/task_template.py

WHAT:
Clustered errors were only showing a max of 10 errors each time do to a logic error with server side pagination.

Fix bug where only 10 errors were showing in clustered errors

---

docsource/monitoring_debugging.rst
jobmon_gui/src/assets/content/JobmonAtIhme.md
jobmon_gui/src/screens/JobmonAtIhme.tsx

You can see the changes displayed here: https://jobmon.readthedocs.io/en/feat-gbdsci-6565-add-db-api-functionality-to-docs/monitoring_debugging.html#jobmon-database-api

Add DB API info to docs

---

jobmon_gui/src/components/task_details/TaskInstanceTable.tsx
jobmon_gui/src/components/workflow_details/WorkflowHeader.tsx
jobmon_gui/src/screens/TaskDetails.tsx

Sets `cursor: 'pointer'` for hover of (i) info icons if/when it is the type where user needs to click in order to see info (e.g. info is hidden in modal) so that user immediately intuits that a click is required to display the information. Also decided to add tooltips (using our custom `HtmlTooltip` component to wrap) for each of these.
Minor GUI update
- Adds `cursor: 'pointer'` style to `HiInformationCircle` info icons where user needs to click in order to see info
- Adds `HtmlTooltip` wrap to these icons with appropriate titles
https://github.com/user-attachments/assets/9ae060e3-7e60-46b4-aaa3-86e845b36dd0
Unlike [this concurrent branch](https://github.com/ihmeuw-scicomp/jobmon/tree/feat/GBDSCI-6554_task-instance-table-clickability), I have not made a `common` component (e.g. with …

Tooltips and cursor as pointer for applicable info icons

---

jobmon_core/src/jobmon/core/task_generator.py

In my experience this has usually turned out to be a mistake.

Warn if the user provides no naming_args.

---

jobmon_gui/src/components/task_details/TaskDAG.tsx
jobmon_gui/src/components/workflow_details/WorkflowDAG.tsx

WHAT:
- There was an error where the dag viz would endlessly spin if a DAG had a single task template with no edges. Removed that check
- Changed it so the workflow DAG viz takes up the whole screen

Fix dag viz problems

---

jobmon_server/src/jobmon/server/web/error_log_clustering.py

WHAT:
Jobmon stores two types of errors in two locations in the database:
- Jobmon application errors are in task_instance_error_log.description. These include things like resources scaling messages etc
- User application errors are in task_instance.stderr_log
Previously we only clustered errors on the second type. This PR changes it so if there are no user errors found in the task_instance table, we will cluster jobmon errors from the task_instance_error_log table.

Change clustered error handling

---

jobmon_core/src/jobmon/core/task_generator.py
jobmon_core/src/jobmon/worker_node/cli.py
tests/worker_node/test_task_generator.py

UI improvement: remove ``--args`` separator between each TaskGenerator parameter. Turns command from something like:
```
worker_node_entry_point task_generator --module_name fhs_lib_file_interface.run.task --func_name finalize_provenance_stage --args log_level='DEBUG' --args stage_key='met_need_weights' --args scenario_id='None' --args scenario_version_number='None' --args output_area='nightly'
```
To:
```
worker_node_entry_point task_generator --module_name fhs_lib_file_interface.run.task --func_name finalize_provenance_stage log_level='DEBUG' stage_key='met_need_weights' scenario_id='None' scenario_version_number='None' output_area='nightly'
```
Manually verified on: https://jobmon-gui.ihme.washington.edu/#/workflow/400015

[FORENG-6782] remove ``--args`` separator from task template

---

CHANGELOG.md
jobmon_core/src/jobmon/core/task_generator.py
tests/worker_node/test_task_generator.py

Passes the upstream_tasks arg through from TaskGenerator.create_task(s) to TaskTemplate.create_task(s)

Adding upstream_tasks to TaskGenerator create_task and create_tasks

---

CHANGELOG.md
jobmon_gui/src/components/task_details/TaskDAG.tsx
jobmon_gui/src/components/task_template_details/ClusteredErrors.tsx
jobmon_gui/src/screens/TaskDetails.tsx

- Added a link to the TaskDetails page from the clustered errors modal (per helpdesk request)
- Swapped the location of the DAG viz and TaskInstance table on the Task Details page (per slack request)
- Fixed broken home button on TaskDetails page (I noticed it and was in the file so fixed it)
- Changed tasks in "G" state (registering) to white in Task DAG viz

Fix jobmon gui bugs

---

jobmon_gui/src/utils/DayTime.ts

WHAT:
Follow up to a previous datetime fix. Workflow details page would render if you clicked in from the landing page, wouldn't render if you went to the link directly or reloaded the page. 
Needed to extend the .tz() at the top of the file instead of in the function, to make sure that it's available always.

Fix date time bug

---

jobmon_gui/src/components/task_details/TaskInstanceTable.tsx

The error logs were displayed allruntogether, in this task-instance-specific view, making them more or less unreadable. The `<pre>` tag makes them more readable*.
*Note that the modal where these are displayed seems unnecessarily constricting. Error logs tend to be wide.
Side note: The other logs page, the one under "Clustered Errors", should probably be updated to match this one. The Cluster Errors seems to apply a formatter for _Python code_. Error logs are not, in general, Python. Sometimes you get a Python stack trace, and that include bits of Python that can be meaningfully formatted, but it also colorizes some non-Python-code lines incorrectly.
Moreover, it makes sense to have the two log displays display in the same way.

Use `<pre>` to honor line breaks in log output.

---

jobmon_core/src/jobmon/core/constants.py
jobmon_server/src/jobmon/server/web/routes/v2/cli/task.py
jobmon_server/src/jobmon/server/web/routes/v3/cli/task.py

WHAT:
The /task/update_statuses route was occasionally causing locks in the database when it transitioning TaskInstances in to K state. This PR optimizes that sql.
HOW:
- Switched from checking TaskInstanceStatuses that were *not* include, to ones that were included
- Added a check of WorkflowRun ID to the where clause
- Used a subequery to pre-filter TaskInstance IDs and then update them
- Batched the status update to 100 TaskInstances at a time
Note: Changes were added to both v2 and v3 routes, since CLI uses v2 and GUI uses v3

Optimize update_status sql

---

jobmon_server/src/jobmon/server/web/routes/v3/fsm/workflow.py

This was probably being caused by users mistyping their workflow ID in to https://jobmon-gui.scicomp.ihme.washington.edu/#/workflow/<workflow_id>. Since that page calls this route to populate the technical panel with the workflow's concurrency limit.

Handle no row was found when one was expected error

---

CHANGELOG.md
docker-compose.yml
jobmon_gui/src/components/task_template_details/usage/RuntimeMemoryScatterPlot.tsx
jobmon_gui/src/components/task_template_details/usage/Usage.tsx
jobmon_gui/src/components/task_template_details/usage/UsageFilters.tsx
jobmon_gui/src/components/task_template_details/usage/UsagePlotSection.tsx
jobmon_gui/src/hooks/useUsageFilters.ts
jobmon_gui/src/types/Usage.ts
jobmon_gui/src/types/apiSchema.ts
jobmon_server/src/jobmon/server/web/repositories/task_template_repository.py
jobmon_server/src/jobmon/server/web/schemas/task_template.py

Added the following to the resource usage scatter plot:
- Added Task name to the tooltip when a user hovers over a data point
- Added a button that allows users to download a CSV file of all of the resource usage data
- Added a new filter that allows users to filter the scatter plot by Task name

Update resource usage plot based on user request

---

CHANGELOG.md
jobmon_server/src/jobmon/server/web/routes/v2/cli/task.py
jobmon_server/src/jobmon/server/web/routes/v3/cli/task.py
jobmon_server/src/jobmon/server/web/routes/v3/fsm/workflow.py
jobmon_server/src/jobmon/server/web/utils/json_compat.py
tests/pytest/client/test_task.py

Cut off at core version 3.4.23 to use the str format returns; newer version uses the json format.

7121 olderclient support

---

CHANGELOG.md
jobmon_server/src/jobmon/server/web/repositories/task_template_repository.py

This PR isn’t a traditional single-query optimization; it makes a deliberate trade-off: accept a tiny overhead for small workflows (milliseconds to a few hundred ms) to speed up large workflows.
Original raw SQL:
SELECT DISTINCT 
task_template.id,
task_template.name,
task_template_version.id AS task_template_version_id
FROM task
JOIN node ON task.node_id = node.id
JOIN task_template_version ON node.task_template_version_id = task_template_version.id
JOIN task_template ON task_template_version.task_template_id = task_template.id
WHERE 
task.workflow_id = :workflow_id
AND task_template_version.task_template_id = :task_template_id
AND task_template_version.task_template_id = task_template.id
This has already been optimized. However, this performs poorly in corner cases. Example (Jon’s …

Improve get task template detail
