ihmeuw-scicomp/jobmon

jobmon_gui/package-lock.json
jobmon_gui/src/workflow_details_page/task_table.tsx
jobmon_gui/src/workflow_details_page/workflow_details_page.tsx

Fix searching by task status in the task table on the task details page

Fix task table search

---

jobmon_gui/package-lock.json
jobmon_gui/src/task_details_page/node_list.tsx
jobmon_gui/src/task_details_page/task_details.tsx
jobmon_server/src/jobmon/server/web/routes/cli/task.py

- Change the Task Details page to show Task names in stead of IDs
- Add a pop up that shows the details of the task

Change to Task name

---

jobmon_gui/package-lock.json
jobmon_gui/src/jobmon_gui.css
jobmon_gui/src/task_details_page/task_details.tsx
jobmon_gui/src/workflow_details_page/workflow_details_page.tsx
jobmon_gui/src/workflow_overview_page/workflow_overview.tsx

When navigating back to the landing page via breadcrumbs the filters and results are still populated instead of clearing. Also, added a clear button that will clear filters, results, and URL params

keep search filters, add clear button

---

jobmon_gui/package-lock.json
jobmon_gui/src/Modal.tsx
jobmon_gui/src/functions.tsx
jobmon_gui/src/task_details_page/task_fsm.tsx
jobmon_gui/src/task_details_page/task_instance_table.tsx
jobmon_gui/src/workflow_details_page/errors.tsx
jobmon_gui/src/workflow_details_page/workflow_details_page.tsx
jobmon_server/src/jobmon/server/web/models/task.py
jobmon_server/src/jobmon/server/web/routes/cli/task_template.py

- Changed sorting of TaskTemplate progress bar on the WorkflowDetails page from submitted date to ID
- Deleted submitted_date column from the Task table since it hasn't been used since the 2 series
- Changed the errors tab to show dates in PST instead of GMT
- Fixed some random ESLint errors

Fix sorting

---

jobmon_gui/package-lock.json
jobmon_gui/src/workflow_overview_page/workflow_overview.tsx
jobmon_server/src/jobmon/server/web/routes/cli/workflow.py
tests/cli/test_cli_routes.py

See change here: https://jobmon-gui-christina.dev.scicomp.ihme.washington.edu/
Jira Ticket: [GBDSCI-5542](https://jira.ihme.washington.edu/browse/GBDSCI-5542)
OG help desk ticket: https://help.ihme.washington.edu/projects/SCICOMP/queues/custom/164/SCICOMP-829

Add workflow attribute filter to the Jobmon GUI

---

jobmon_client/src/jobmon/client/cli.py
jobmon_client/src/jobmon/client/status_commands.py
jobmon_client/src/jobmon/client/workflow_run.py
jobmon_core/src/jobmon/worker_node/worker_node_task_instance.py
jobmon_server/src/jobmon/server/web/models/workflow_run.py
jobmon_server/src/jobmon/server/web/routes/cli/workflow.py
jobmon_server/src/jobmon/server/web/routes/reaper/reaper.py
tests/cli/test_cli_routes.py
tests/worker_node/test_task_instance_worker_node.py

Only actual code change is in: jobmon_server/src/jobmon/server/web/routes/reaper/reaper.py. Besides that it's just changes for linting

Fix reaper bug and fix lining

---

jobmon_server/src/jobmon/server/web/routes/__init__.py
tests/cli/test_cli_routes.py
tests/cli/test_resource_api.py
tests/cli/test_status_commands.py
tests/client/test_array.py
tests/client/test_task.py
tests/client/test_task_resources.py
tests/client/test_workflow.py
tests/core/test_cluster_queue.py
tests/distributor/test_instantiate.py
tests/server/test_database_schema.py
tests/swarm/test_swarm.py
tests/swarm/test_swarm_task.py
tests/worker_node/test_task_instance_worker_node.py
tests/workflow_reaper/test_workflow_reaper.py

After SQLAlchemy version update we had ~35 failing tests in the test suite, this PR makes the test suite pass again.

Get test suite back online

---

jobmon_core/pyproject.toml
jobmon_core/src/jobmon/distributor/distributor_service.py

As a comment, copilot was _very_ nice in developing this PR

first pass of asyncio in distributor

---

jobmon_core/src/jobmon/core/defaults.ini
jobmon_core/src/jobmon/core/requester.py

Change retries so that they utilize only wait exponential with a jitter and a max time of 5 min. set defaults

improve retries

---

jobmon_core/pyproject.toml
jobmon_core/src/jobmon/core/constants.py
jobmon_core/src/jobmon/distributor/distributor_service.py
jobmon_server/pyproject.toml
jobmon_server/src/jobmon/server/web/models/task_instance.py
jobmon_server/src/jobmon/server/web/models/task_instance_status.py
jobmon_server/src/jobmon/server/web/routes/fsm/task_instance.py
jobmon_server/src/jobmon/server/web/routes/fsm/workflow_run.py
tests/conftest.py
tests/distributor/test_triaging.py

Still have to run unit/load tests and such, but this is a proposal to review in parallel.

first commit of proposed fsm change

---

jobmon_gui/src/pages/workflow_details_page/workflow_details_page.tsx
jobmon_gui/src/pages/workflow_overview_page/workflow_overview.tsx

Fix problem in landing URL
Fix deleted line that didn't set jobmon version

Fix bugs in GUI

---

jobmon_core/src/jobmon/core/configuration.py
jobmon_core/src/jobmon/core/otlp.py
jobmon_core/src/jobmon/core/requester.py
jobmon_core/src/jobmon/distributor/distributor_service.py
mypy.ini

I'll make follow up tasks for client and server

jobmon_core typecheck now working

---

jobmon_client/src/jobmon/client/node.py
jobmon_client/src/jobmon/client/task.py
jobmon_server/src/jobmon/server/web/_compat.py
jobmon_server/src/jobmon/server/web/api.py
jobmon_server/src/jobmon/server/web/app_factory.py
jobmon_server/src/jobmon/server/web/hooks_and_handlers.py
jobmon_server/src/jobmon/server/web/log_config.py

Fixed the random jobmon_server typechecking errors that were left. jobmon server is now passing typecheck.

Jobmon server is now passing typecheck

---

jobmon_client/src/jobmon/client/task_resources.py
jobmon_client/src/jobmon/client/workflow.py
jobmon_core/src/jobmon/core/defaults.yaml

I think mypy is just being unreasonable to disagree with scalar being a number.Number, so type ignored them.
Run these:
- nox -s black
- nox -s lint
- mypy --explicit-package-bases jobmon_client
- pytest tests/client

Gbdsci 6050 client type check

---

jobmon_gui/.env
jobmon_gui/src/components/Modal.tsx
jobmon_gui/src/css/jobmon_gui.css
jobmon_gui/src/pages/workflow_details_page/wf_header.tsx
jobmon_server/src/jobmon/server/web/routes/v2/cli/workflow.py

Fixed two bugs:
- Nav bar was going over modal and users couldn't see error logs
- Empty where statement in workflow SQL that was causing APM errors

Fix GUI bugs

---

jobmon_client/pyproject.toml

try and update the package name

---

jobmon_core/src/jobmon/core/__init__.py

This should fix jobmonr without building a new jobmonr.

Remove my debug code

---

jobmon_client/src/jobmon/client/workflow.py

LMK if there's a constant somewhere which has the URL format.

Include GUI link while reporting the newly-generated workflow ID

---

jobmon_server/src/jobmon/server/web/routes/v2/fsm/node.py

passes local nox lint and nox tests

refactored node route to use separate session for separate db insert

---

jobmon_gui/src/components/workflow_details/WorkflowHeader.tsx
jobmon_gui/src/screens/TaskDetails.tsx
jobmon_gui/src/screens/WorkflowDetails.tsx

Change Workflow Information on Workflow Details from a hover zoom to a information click button.

GBDSCI 6258

---

jobmon_gui/src/components/task_details/TaskInstanceTable.tsx
jobmon_server/src/jobmon/server/web/routes/v2/cli/task.py

GBDSCI-6272: Add memory and runtime to task instance table

---

jobmon_gui/src/components/workflow_overview/WorkflowStatus.tsx
jobmon_gui/src/screens/WorkflowOverview.tsx

- Default to only showing workflows that were submitted in the last two weeks
- Code cleanup (there could probably be more done in the future)

GBDSCI-6278

---

docsource/advanced_usage.rst

Looks like we already had a doc section for this functionality. I updated it and also removed a confusing code block in the resume section.

GBDSCI-6026

---

jobmon_gui/CHANGELOG.md
jobmon_gui/package.json

We may want to have Jobmon and Jobmon GUI be in one CHANGELOG instead of two

Update changelog and tag

---

jobmon_gui/local_testing/jobmon_gui/testing_servers/functionaltest_server.py
jobmon_gui/src/screens/WorkflowOverview.tsx
jobmon_server/src/jobmon/server/web/routes/v2/cli/workflow.py
tests/cli/test_cli_routes.py

Allow users to filter by both workflow attribute key and value

GBDSCI 6283

---

jobmon_gui/src/components/workflow_details/Errors.tsx
jobmon_gui/src/components/workflow_details/TaskTable.tsx
jobmon_gui/src/components/workflow_overview/WorkflowTable.tsx
jobmon_gui/src/screens/TaskDetails.tsx
jobmon_gui/src/screens/WorkflowDetails.tsx
jobmon_gui/src/screens/WorkflowOverview.tsx

Fix bug in home button on Jobmon GUI

Gbdsci 5555

---

jobmon_gui/CHANGELOG.md
jobmon_gui/src/screens/WorkflowDetails.tsx

- Fixed elapsed workflow time
- Updated changelog

Fix elapsed time

---

jobmon_server/src/jobmon/server/web/routes/v2/fsm/tool.py

Added a route that returns node args and resource usage information for all task instances associated with a tool.

Gbdsci 6390

---

jobmon_core/pyproject.toml

https://ihme.slack.com/archives/C8XGKCLQ1/p1721410090965259

Ping down grpcio

---

jobmon_gui/src/components/workflow_overview/WorkflowList.tsx

This is to fix the GUI end submit date not including the selected date issue.

Add one day to the submitted end date

---

docsource/advanced_usage.rst
docsource/task-generator.rst
jobmon_gui/package-lock.json
jobmon_gui/src/screens/WorkflowDetails.tsx

Looks a different PR/merge conflicts wiped out this bug fix. Adding it back.

Refix elapsed time

---

jobmon_gui/CHANGELOG.md
jobmon_gui/src/components/workflow_details/Usage.tsx

Histograms (both runtime and memory) weren't showing anything. Date returned by route wasn't being accessed properly.

Fix histograms and update changelog

---

jobmon_gui/package-lock.json
jobmon_gui/src/components/JobmonProgressBar.tsx

In the hover pop up on the TaskTemplate progress on the Workflow Details page the `concurrency limit` would show as false when it was set instead of the value e.g. 5000. This PR fixes that.

Fix bug with concurrency limit

---

jobmon_gui/CHANGELOG.md
jobmon_gui/package-lock.json
jobmon_gui/package.json
jobmon_gui/src/assets/content/JobmonAtIhme.md
jobmon_gui/src/components/JobmonProgressBar.tsx
jobmon_gui/src/components/workflow_details/ClusteredErrors.tsx
jobmon_gui/src/components/workflow_details/TaskTable.tsx
jobmon_gui/src/components/workflow_details/Usage.tsx
jobmon_gui/src/components/workflow_overview/WorkflowList.tsx
jobmon_gui/src/screens/JobmonAtIhme.tsx
jobmon_server/src/jobmon/server/web/routes/v2/cli/task_template.py

PR I:
Remove invalid date from workflow information modal
PR II:
Status date in task table on workflow details page was showing in UTC instead of PDT/PST. This PR fixes that.
PR III:
Histograms (both runtime and memory) weren't showing anything. Date returned by route wasn't being accessed properly.
PR IV:
Clustered errors were only showing a max of 10 errors each time do to a logic error with server side pagination. This PR fixed that.
PR V:
Fix bug with concurrency limit - In the hover pop up on the TaskTemplate progress on the Workflow Details page the concurrency limit would show as false when it was set instead of the value e.g. 5000. This PR fixes that.
PR VI:
Changed the error message in the pop up modal to add newlines and syntax highlighting. Also added a button so users can …

Consolidated down all bugfixes

---

jobmon_server/src/jobmon/server/web/routes/v2/fsm/workflow.py

Added a new route which will hopefully enable CC to get the needed TaskInstance resource usage that they need.

Add new DB API route

---

jobmon_core/src/jobmon/core/defaults.yaml
jobmon_gui/README.md
jobmon_gui/local_testing/jobmon_gui/testing_servers/_create_sqlite_db.py
jobmon_gui/local_testing/jobmon_gui/testing_servers/functionaltest_server.py
jobmon_server/src/jobmon/server/web/api.py
noxfile.py
tests/conftest.py
tests/server/conftest.py

improve gui test server startup

---

CHANGELOG.md
jobmon_gui/CHANGELOG.md
jobmon_gui/README.md

Small PR to update changelog, so I remember what to add to deployment notes.

Update changelog for 3.4

---

jobmon_core/src/jobmon/core/task_generator.py
tests/worker_node/test_task_generator.py

Addresses: https://github.com/ihmeuw-scicomp/jobmon/issues/239

[FORENG-6051] bugfix: properly handle deserialization of empty strings

---

jobmon_core/src/jobmon/core/task_generator.py

Addresses: https://github.com/ihmeuw-scicomp/jobmon/issues/252
Old look:
New look:

[FORENG-6774] correct taskgenerator sphinx extension

---

CHANGELOG.md
jobmon_gui/src/components/workflow_details/WorkflowHeader.tsx

Added more information about what happens when users stop a workflow and update task status to the technical panel in the Jobmon GUI.

Add more information to technical panel

---

jobmon_server/src/jobmon/server/web/repositories/task_template_repository.py
jobmon_server/src/jobmon/server/web/routes/v3/cli/task.py
jobmon_server/src/jobmon/server/web/routes/v3/fsm/array.py
tests/pytest/client/test_array.py

Try to fix this dead lock: https://kibana.aks.scicomp.ihme.washington.edu/app/apm/services/jobmon/errors/ace9118a1b79b3e1?comparisonEnabled=true&environment=prod&kuery=&latencyAggregationType=avg&offset=1d&page=0&pageSize=50&rangeFrom=2025-09-30T22:02:10.735Z&rangeTo=now&serviceGroup=&sortDirection=desc&sortField=occurrences&transactionType=request&errorId=7f8e96ac2af2c4f89b00cc629e31f758
by
1. Loose the retry rules;
2. Lock the rows before update, but do not wait for locks
3. Add two test cases to a. call the same route at the same time; b. call queue task batch and log done at the same time

Missed deadlock in array
